[book]
authors = ["Lorenz Schmidt", "Christopher Moran"]
language = "en"
multilingual = false
src = "src"
title = "Rust Machine Learning Book"

[output.html]
# Mathjax support addition
mathjax-support = true
